# Generated by Django 2.2.4 on 2020-09-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='gitHub',
            field=models.URLField(blank=True),
        ),
    ]
