# Generated by Django 2.2.4 on 2020-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_personaldetail_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
