# Generated by Django 2.2.4 on 2020-10-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_personaldetail_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='istitutionName',
            new_name='institutionName',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='cv_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('D', 'Development'), ('P', 'Production')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
